#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ "$SHLVL" -eq 1 && ! -o LOGIN && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

export PATH=~/bin:~/bin/drush:usr/local/share/npm/bin:/usr/local/bin:$PATH
#custom settings for homebrew-php pear
export PATH="$(brew --prefix php53)/bin:$PATH"
